### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by MattDMo** [facelessuser/ColorSchemeEditor#11]
Hi Isaac,
I know you don't like doing documentation until you're ready, but would you mind posting some (at least rudimentary) build instructions when you have a chance? I know you've been making a lot of changes recently, and especially with the issues the Sublime Forum has been having recently I haven't been able to see if you've posted a new build recently or not. I'd love to be able to hack on this a little myself, and build on my own.

Thanks!
Matt

PS:
Once you're ready for prime time and submit this to Package Control, I think you're going to get a lot of users very quickly. I built my themes originally using TextMate 1, but that doesn't work when I'm away from my Mac (which is at home), and TM butchers any custom global values you put in beyond what it supports. [tmTheme-Editor](http://tmtheme-editor.herokuapp.com/) is nice, but only supports JavaScript highlighting, and the regexen aren't the same as Sublime's. You ColorSchemeEditor is just absolutely fantastic, I love it! I've been at work so much lately I haven't had time to work on my color schemes much, but this tool is wonderful! :)

**Comment by facelessuser** [comment]
I may be ditching PyInstaller support moving forward.

If  I do this, assuming you have wxPython installed, you should be able to simply pull the package and say:

```
python setup.py build
python setup.py install
```

If developing, you could also do something like this and you would always have your changes accessible globally:

```
pip install --editable .
```

I guess you could also just say for a non developer install (haven't tried that):

```
pip install .
```

This support already exists, but the ColorSchemeEditor plugin is not yet aware of this install method.  It is possible that I will make this the only way moving forward as building linux, windows, and OSX binaries is exhausting.  Linux binaries more so as often those are the ones that give me the most trouble in distribution.

ColorSchemeEditor may still check the version, and warn the user when they are out of date, but it would be the users responsibility to update to the latest.

**Comment by facelessuser** [comment]
Build instructions are being done away with as I am going to kill PyInstaller support.

Moving forward, I will require people to just install the package into their system Python.  That way I don't have to build binaries, and nor do you.

Source for tool is not at https://github.com/facelessuser/subclrschm.  Supports WxPython 3.0.2 now. Probably broke some backwards compatibility stuff with 2.9.4.  Travis CI is complaining about lint; I'll get to it tomorrow probably. Assuming Python 2.7 is being used, current install instructions are now:

```
python setup.py build
python setup.py install
```

If you are playing around with the source, you can do this from the project root instead, and all changes should be picked up without building:

```
pip install --editable .
```

The sublime plugin will do away with pulling down binaries and require people to have the tool in their path, maybe allow them to specify an absolute path.  Anyways, this should be much easier to maintain for me.  And not nearly as hard for other people to install manually.

**Comment by facelessuser** [comment]
Went ahead and got things solid again.  I am going to close this issue in favor of #16.  As this build instructions are no longer needed, but documentation in general is.
